name: Auto Test

on:
  push:
    branches: 
    - assignment_4

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run test on MacOS latest
      run: make test
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu latest
      run: make test
  test-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu 18.04
      run: make test
  test-ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu 16.04
      run: make test
