name: Auto Test

on:
  push:
    branches: 
    - assignment_4

jobs:

  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run test on MacOS latest
      run: make test

  test-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu latest
      run: make test

  test-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu latest
      run: make test

  test-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu 18.04
      run: make test

  test-mutex-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run test on MacOS latest
      run: make use_mutex.debug test

  test-mutex-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu latest
      run: make use_mutex.debug test

  test-mutex-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu latest
      run: make use_mutex.debug test

  test-mutex-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test on Ubuntu 18.04
      run: make use_mutex.debug test
